name: My Work Pipeline
on: [pull_request]
jobs:
  extract-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: read from test md
        id: pyhton-script
        uses: jannekem/run-python-script-action@v1

      - name: fetch file name
        id: featch-file-name
        run: |
          gh pr view 2
        
        
        
        
